exports.error = require('./ErrorManager'); // todo : move to services
exports.log = require('./LogManager'); // todo : remove this. no need for this
exports.users = require('./UsersManager');
exports.questions = require('./QuestionsManager');
exports.lessons = require('./LessonsManager');
exports.lessonsInvitations = require('./LessonsInvitationsManager');
exports.reports = require('./ReportsManager');
exports.abuseReports = require('./AbuseReportsManager');
exports.classReports = require('./ClassReportsManager');
exports.roles = require('./RolesManager');
